In [ ]:
import pandas as pd
import json
import numpy as np
import altair as alt

db_item = pd.read_csv('C:/Users/juanx/Downloads/forWeb/db_item_clean.csv')
db_item

# Cast date_quote_s and date_quote_e to date type and format yyyymm

,item_id,description,date_quote_s,date_quote_e,n_obs
0,210101,LARGE LOAF-WHITE-SLICED-800G,198802,200401,36039
1,210102,LARGE LOAF-WHITE-UNSLICED-800G,198802,202511,56987
2,210105,LARGE WHOLEMEAL LOAF-UNSLICED,198802,200301,27161
3,210106,SIX BREAD ROLLS-WHITE/BROWN,198802,202511,67610
4,210107,"BROWN LOAF,400G,SLICED-GRAN",198903,200401,29361
...,...,...,...,...,...
1382,640233,LEISURE CENTRE MEMBERSHIP,200302,201201,17695
1383,640240,LIVERY CHARGES PER WEEK,200802,202511,21647
1384,640243,SOFT PLAY SESSION TIME PERIOD,201802,202511,11239
1385,640244,CLIMBING WALL SESSION,202202,202511,2197
1386,640406,HOTEL 1 NIGHT PRICE,200502,202511,27479

In [4]:
db_prices = pd.read_csv('C:/Users/juanx/Downloads/forWeb/db_prices.csv')
db_prices

,quote_date,shop_code,item_id_raw,region,price,indicator_box,item_id
0,200206.0,9.0,210101,3.0,0.69,Q,210101
1,199901.0,937.0,210101,13.0,0.45,NaN,210101
2,199211.0,16.0,210101,9.0,0.54,NaN,210101
3,199606.0,187.0,210101,8.0,0.77,NaN,210101
4,200204.0,807.0,210101,8.0,0.39,Q,210101
...,...,...,...,...,...,...,...
48500746,202312.0,16599.0,640406,3.0,60.00,NaN,640406
48500747,201110.0,5262.0,640406,4.0,170.00,NaN,640406
48500748,200902.0,465.0,640406,5.0,60.00,NaN,640406
48500749,201712.0,654.0,640406,2.0,305.00,NaN,640406
48500750,201405.0,542.0,640406,2.0,60.00,NaN,640406

In [5]:
db_itemWeights = pd.read_csv('C:/Users/juanx/Downloads/forWeb/db_itemWeights.csv')
db_itemWeights

        quote_date   item_id  coicop_weight  dup
0         199602.0  210101.0           2.75    0
1         199603.0  210101.0           2.75    0
2         199604.0  210101.0           2.75    0
3         199605.0  210101.0           2.75    0
4         199606.0  210101.0           2.75    0
...            ...       ...            ...  ...
197327    202011.0  640407.0          10.80    0
197328    202012.0  640407.0          10.80    0
197329    202101.0  640407.0          10.80    0
197330    202102.0  640407.0           8.10    0
197331         NaN       NaN            NaN    0

[197332 rows x 4 columns]

In [6]:
db_region = pd.read_csv('C:/Users/juanx/Downloads/forWeb/db_region.csv')
db_region

,region_n,region_s,region,country,obs,p_min,p_max,p_mean,p_med,p_sd
0,1,Catalogue collections,Catalogue,NaN,306968,0.12,1999,41.329037,22.00,80.908554
1,2,London,London,England,4475848,0.01,20000,56.248341,4.60,246.010300
2,3,South East,South East,England,5785278,0.01,9499,54.609386,4.90,220.251300
3,4,South West,South West,England,3597289,0.01,6950,50.904106,4.50,201.636340
4,5,East Anglia,East Anglia,England,3204009,0.01,7650,51.067471,4.69,197.143280
5,6,East Midlands,East Midlands,England,2976879,0.01,10250,46.733604,4.07,194.929810
6,7,West Midlands,West Midlands,England,3518149,0.01,7650,43.581417,4.00,172.725430
7,8,Yorkshire & Humber,Yorkshire & Humber,England,3408323,0.01,20895,45.889851,4.29,183.482450
8,9,North West,North West,England,4294065,0.01,9310,42.274700,3.99,174.610350
9,10,North,North,England,2321737,0.01,9222,40.915108,3.99,166.738360
10,11,Wales,Wales,Wales,2216742,0.01,7347,38.699127,3.99,147.970580
11,12,Scotland,Scotland,Scotland,3385786,0.01,7999,42.445091,4.38,168.262510
12,13,Northern Ireland,Northern Ireland,Northern Ireland,1518537,0.01,6995,44.438995,5.00,163.047960

In [7]:
db_date = pd.read_csv('C:/Users/juanx/Downloads/forWeb/db_date.csv')
db_date

,date,quote_date,obs_panel,obs,date2,date3,date4,year,year_s,month,...,p_med,p_sd,day,day_s,cpiindex00allitems2015100,cpiindex01foodandnonalcoholicbev,cpiindex02alcoholicbeveragestoba,cpiindex011food2015100,cpiindex012nonalcoholicbeverages,cpi00_adjustment
0,1,198802,35459.0,51065,01-02-1988,01-02-1988,1988-02-01,1988,1988,2,...,1.35,54.338814,1,1,48.6,48.3,27.4,48.5,45.9,1.000000
1,2,198803,35240.0,49987,01-03-1988,01-03-1988,1988-03-01,1988,1988,3,...,1.30,51.615620,1,1,48.7,48.4,27.5,48.6,46.2,1.002058
2,3,198804,36066.0,51716,01-04-1988,01-04-1988,1988-04-01,1988,1988,4,...,1.35,53.485882,1,1,49.3,48.7,27.9,48.9,46.6,1.014403
3,4,198805,35869.0,51209,01-05-1988,01-05-1988,1988-05-01,1988,1988,5,...,1.35,53.936596,1,1,49.5,48.8,28.0,49.0,47.2,1.018519
4,5,198806,35811.0,51126,01-06-1988,01-06-1988,1988-06-01,1988,1988,6,...,1.38,53.684380,1,1,49.7,48.9,28.0,49.0,47.7,1.022634
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
449,452,202509,114123.0,130411,01-09-2025,01-09-2025,2025-09-01,2025,2025,9,...,6.50,303.625820,1,1,139.3,142.5,156.3,141.7,149.0,2.866255
450,453,202510,114645.0,131244,01-10-2025,01-10-2025,2025-10-01,2025,2025,10,...,6.55,305.483550,1,1,139.8,143.2,156.8,142.5,149.2,2.876543
451,454,202511,115124.0,131778,01-11-2025,01-11-2025,2025-11-01,2025,2025,11,...,6.63,304.080570,1,1,139.5,142.9,156.1,142.1,149.4,2.870370
452,7,198808,NaN,0,01-08-1988,01-08-1988,1988-08-01,1988,1988,8,...,NaN,NaN,1,1,49.9,48.7,28.0,48.7,48.5,1.026749
453,13,198902,NaN,0,01-02-1989,01-02-1989,1989-02-01,1989,1989,2,...,NaN,NaN,1,1,51.0,50.2,28.5,50.2,49.7,1.049383